Fix login bug
YunoHost-Apps/radarr_ynh pull request #30
Opened 2023-10-21 12:18 UTC by mh4ckt3mh4ckt1c4s

## Problem

- Seems that login was made mandatory recently in Radarr. However the YNH Radarr app is not working with Form and Basic auth currently (see [this bug](https://forum.yunohost.org/t/radarr-connection-refused-when-i-set-login-type-to-form/19501)). This is due to a lacking HTTP Header (`Host`), as explained in https://github.com/Radarr/Radarr/issues/6906#issuecomment-1006529239.

## Solution

- Adding the `Host` header in nginx conf. 

## PR Status

- [X] Code finished and ready to be reviewed/tested
- [X] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2023-10-21 13:04 UTC, tituspijean commented
We will need to check that the Host header won't clash with the expected External setting (instead of Form or Basic).

Is there a reason to force `Host __DOMAIN__`  instead of a usual `Host $host`?

2023-10-21 13:15 UTC, mh4ckt3mh4ckt1c4s commented
`Host $host` should also work. I messed up my nginx and radarr config while experimenting and came up with this solution, but $host with a correct radarr config should do the trick.

2023-10-25 16:05 UTC, tituspijean requested changes

2023-10-25 16:05 UTC, tituspijean commented on conf/nginx.conf
> +  proxy_set_header Host __DOMAIN__;
```suggestion
  proxy_set_header Host $host;
```

2023-10-29 14:58 UTC, tituspijean approved these changes

2023-10-29 14:58 UTC, merged